deps = "sha256-YWqqvdlh/HDrNd6o/FS4V/sAmGFaJ8v7HGn6xmVjsFM="
cargo_config = '''
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/snapshot_browser_deps_6f79d2ed-822d-4234-8ce0-75964acc7b06"'''
cargo_lock = "0ebca4016a14298af62caac66375181beae3f2be33efa30c8e6f6d77fba09d10"
