deps = "sha256-JDXjlpFvh1jQQrD2xt+klgweGgNKa5s3I/EtKgDU6yQ="
cargo_config = '''
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/snapshot_browser_deps_f300431f-2463-41be-9969-b3b501ce8dd1"'''
cargo_lock = "8a8b68fbcf4d3662ea07d50be18a781d4705a26380da6de19822bccac799eedf"
