deps = "sha256-cmJB4i2pdKtt40UxtPLXl7wC1L4/FndOtXFNDOxROb0="
cargo_config = '''
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/snapshot_browser_deps_0404c1cc-311f-481c-be23-bc3814e24de1"'''
cargo_lock = "eff814ae7070a56f0e45e1e0236db79c1bab929028c5f7dc4d8394139bac5bf0"
